services:
    mysql:
        image: 'mysql:8.1'
        container_name: db
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
            - vol_books:/var/lib/mysql
        environment:
            - 'MYSQL_DATABASE=db_books'
            - 'MYSQL_ROOT_PASSWORD=secret'
            - 'MYSQL_USER=cesar'
            - 'MYSQL_PASSWORD=cesar'
        ports:
            - '3306:3306'
volumes:
    vol_books:
        name: "vol_books"