services:
    mysql:
        image: 'mysql:8.1'
        container_name: db
        volumes:
#            - ./init.sql:/docker-entrypoint-initdb.d/init.sql # leia instructions.txt
            - vol_bookstore:/var/lib/mysql
        environment:
            - 'MYSQL_DATABASE=${MYSQL_DATABASE}'
            - 'MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}'
            - 'MYSQL_USER=${MYSQL_USER}'
            - 'MYSQL_PASSWORD=${MYSQL_PASSWORD}'
        ports:
            - '3306:3306'
volumes:
    vol_bookstore:
        name: "vol_bookstore" # Set volume name