services:
    mysql:
        image: 'mysql:8.1'
        container_name: db
        volumes:
            - vol_books:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - '3306:3306'
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
            interval: 10s
            timeout: 5s
            retries: 3
        networks:
            - bookstore-network
    bookstore-app:
        image: bookstore-app:1.0
        container_name: bookstore
        build: .
        depends_on:
            mysql:
                condition: service_healthy
        ports:
            - '8080:8080'
        environment:
            SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
            SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
            SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
        networks:
            - bookstore-network
volumes:
    vol_books:
        name: "vol_books"
networks:
    bookstore-network:
        name: "bookstore-network"
        driver: bridge